#!/usr/bin/perl


# $Revision$ 
# $Date$ 
# $Author$ 
# $Source$ 
# $Name$ 

$t=time();

$out= (
       "The current time on ".`hostname`. "\n".
       "UnixTime: ".$t."\n".
       "LocalTime: ".localtime($t)."\n".
       "GMTime: ".gmtime($t)."\n".
       "\n"
	       );

print $out;
