/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is the Mozilla SIP client project.
 *
 * The Initial Developer of the Original Code is 8x8 Inc.
 * Portions created by the Initial Developer are Copyright (C) 2005
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *   Alex Fritze <alex@croczilla.com> (original author)
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "nsISupports.idl"

interface zapISipConnection;
interface zapISipFlowMonitor;

/**
 * \ingroup SIP_TRANSPORT_LAYER
 * Describes a network protocol layer connection between two hosts.
 *
 * Flow objects are managed by the the transport layer, see
 * zapISipTransport.
 *
 * Clients can add monitor callbacks to flows to observe the
 * connectivity status and keep alive a connection through NAT.
 */
[scriptable, uuid(9e26bde0-4181-4724-abbe-39f61a15c3bb)]
interface zapISipFlow : nsISupports
{
  /**
   * IP address of local endpoint
   */
  readonly attribute ACString localAddress;

  /**
   * Port of local endpoint
   */
  readonly attribute unsigned short localPort;

  /**
   * IP address of remote endpoint
   */
  readonly attribute ACString remoteAddress;

  /**
   * Port of remote endpoint
   */
  readonly attribute unsigned short remotePort;

  /**
   * Transport protocol to remote endpoint (udp, tcp, ...)
   */
  readonly attribute ACString transportProtocol;

  /**
   * Connection object of the flow (null for connection-less protocols)
   */
  readonly attribute zapISipConnection connection;

  /**
   * Monitor the flow using periodic STUN binding requests as
   * specified in draft-ietf-sip-outbound-01
   */
  const unsigned short IETF_SIP_OUTBOUND_01_MONITOR = 0x0001;

  /**
   * Monitor the flow by sending periodic OPTIONS requests.
   *
   * OPTIONS monitoring will only be available if the transport layer
   * has been initialized with a zapISipUAStack. See
   * zapISipTransport::UAStack
   */
  const unsigned short OPTIONS_MONITOR              = 0x0002;

  void addFlowMonitor(in zapISipFlowMonitor monitor, in unsigned short type);
  void removeFlowMonitor(in zapISipFlowMonitor monitor);
};
