/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is the Mozilla SIP client project.
 *
 * The Initial Developer of the Original Code is 8x8 Inc.
 * Portions created by the Initial Developer are Copyright (C) 2005
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *   Alex Fritze <alex@croczilla.com> (original author)
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "nsISupports.idl"

interface zapISipCredentialsProvider;
interface zapISipRequest;
interface zapISipResponse;

/**
 * \ingroup SIP_UA_LAYER
 * SIP authentication API compliant to RFC3261 section 22/RFC2617
 *
 * Implemented by component <b>'\@mozilla.org/zap/sipauth;1'</b>
 */
[scriptable, uuid(36ce7b69-ab76-433f-8b3c-83e16b379afc)]
interface zapISipAuthentication : nsISupports
{
  /**
   * \name authFlags flag constants for addAuthorizationHeaders
   */
  //@{

  /**
   * Some servers (most notably some common versions of Asterisk)
   * forget to set the nonce=stale parameter when rejecting a request
   * with a stale nonce. When ASTERISK_STALE_NONCE_HACK is set,
   * addAuthorizationHeaders() will compare the nonces of request and
   * response, and when they don't match, set the
   * hasRejectedCredentials parameter to getCredentialsForRealm() to
   * false.
   *
   */
  const unsigned long ASTERISK_STALE_NONCE_HACK = 0x0001;
  
  //@}
  
  /**
   * Add authorization headers to 'request' for all WWW-Authenticate
   * and Proxy-Authenticate challenges in 'response' for which
   * 'credentials' has appropriate credentials.  Returns 'true' if new
   * authorization headers have been added
   */
  boolean addAuthorizationHeaders(in zapISipCredentialsProvider credentials,
                                  in zapISipResponse response,
                                  in zapISipRequest request,
                                  in unsigned long authFlags);
};


[scriptable, uuid(77a4000e-cc95-471e-8833-8c4ebcd2fb3b)]
interface zapISipCredentialsProvider : nsISupports
{
  boolean getCredentialsForRealm(in ACString realm,
                                 inout wstring username,
                                 inout wstring password,
                                 in boolean hasRejectedCredentials);
};
