DEPTH = ../../../..

include $(DEPTH)/config.mk
include $(DEPTH)/liveconnect/config/$(OS_CONFIG).mk

JAVA_SRCS = JSException.java \
            JSObject.java    \
            JSProxy.java     \
            JSRunnable.java  \
            JSUtil.java

include $(DEPTH)/rules.mk
