<!--
     The contents of this file are subject to the Mozilla Public License
     Version 1.0 (the "License"); you may not use this file except in
     compliance with the License. You may obtain a copy of the License at
     http://www.mozilla.org/MPL/

     Software distributed under the License is distributed on an "AS IS"
     basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
     License for the specific language governing rights and limitations
     under the License.

     The Original Code is the Bugzilla Bug Tracking System.

     The Initial Developer of the Original Code is Netscape Communications
     Corporation. Portions created by Netscape are Copyright (C) 1998
     Netscape Communications Corporation. All Rights Reserved.

     Contributor(s): Terry Weissman <terry@mozilla.org>
                     Andrew Anderson <andrew@redhat.com>
-->
<?include "header.html" ?>

<TABLE BORDER=0 CELLPADDING=12 CELLSPACING=0 WIDTH="100%">
 <TR>

  <TD>

   <TABLE BORDER=0 CELLPADDING=0 CELLSPACING=2>

    <TR><TD VALIGN=TOP ALIGN=CENTER NOWRAP>

     <FONT SIZE="+3"><B><NOBR>Main Page</NOBR></B></FONT>

    </TD></TR><TR><TD VALIGN=TOP ALIGN=CENTER>

     <B></B>

    </TD></TR>

   </TABLE>

  </TD>

  <TD>

   This is <B>Bugzilla</B>: the Red Hat bug system.  For more 
   information about what Bugzilla is and what it can do, see 
   <A HREF="http://www.mozilla.org/">mozilla.org</A>'s
   <A HREF="http://www.mozilla.org/bugs/"><B>bug pages</B></A>.
</TD></TR></TABLE>


<body>

<p>

Go to the <A HREF="query.cgi">query page</A>.<BR>
Enter a <A HREF="enter_bug.cgi">new bug</A>.<BR>
Submit a <A HREF="redhat-faq.phtml#howdoipatch">patch</A>.<BR>
Having problems using bugzilla? Look at the 
  <A HREF="redhat-faq.phtml">FAQ</A>, 
or email <A HREF="mailto:bugzilla-owner@redhat.com">bugzilla-owner@redhat.com</A><BR>
<FORM METHOD="GET" ACTION="show_bug.cgi">
<INPUT TYPE="SUBMIT" VALUE="Show"> bug # <INPUT NAME=id SIZE=6>
</FORM>
</TD>
</TABLE>

<?include "footer.html" ?>
