/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 *
 * The contents of this file are subject to the Netscape Public
 * License Version 1.1 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of
 * the License at http://www.mozilla.org/NPL/
 *
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 *
 * The Original Code is mozilla.org code.
 *
 * The Initial Developer of the Original Code is Netscape
 * Communications Corporation.  Portions created by Netscape are
 * Copyright (C) 2001 Netscape Communications Corporation. All
 * Rights Reserved.
 *
 * Contributor(s): 
 */

#include "nsISupports.idl"
#include "nsISOAPMarshaller.idl"
#include "nsISOAPUnmarshaller.idl"

/**
 * This interface keeps all the info about a type mapping: the encoding style,
 * the XML element type, the marshalling type and the constructor that is
 * supposed to create the type for unmarshalling.
 */
[scriptable, uuid(2c1c105c-1dd2-11b2-8b8a-f5137f365679)]
interface nsISOAPType : nsISupports {

/**
 * Encoding style
 */
  attribute DOMString encodingStyleURI;

/**
 * Type of parameter marshalled / unmarshalled
 */
  attribute DOMString parameterType;

/**
 * Namespace URI of the element of encoding, or null if no namespace URI
 */
  attribute DOMString elementNamespace;

/**
 * Local name of the element of encoding, or null if no namespace URI
 */
  attribute DOMString elementLocalname;

/**
 * Contract ID of service which can marshal this type of object into DOM
 */
  attribute nsISOAPMarshaller marshaller;

/**
 * Contract ID of service which can unmarshal this type of object from DOM
 */
  attribute nsISOAPUnmarshaller unmarshaller;

/**
 * Configuration object that may contain more info on the marshalling
 */
  attribute nsISupports marshallConfiguration;

/**
 * Configuration object that may contain more info on the unmarshalling
 */
  attribute nsISupports unmarshallConfiguration;

};
%{ C++
#define NS_SOAPTYPE_CID                            \
{ /* 4c3ecba2-1dd2-11b2-a3e7-80958e8c4683 */        \
  0x4c3ecba2, 0x1dd2, 0x11b2,                       \
 {0xa3, 0xe7, 0x80, 0x95, 0x8e, 0x8c, 0x46, 0x83} }
#define NS_SOAPTYPE_CONTRACTID \
"@mozilla.org/xmlextras/soap/type;1"
%}
