/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is the Mozilla SIP client project.
 *
 * The Initial Developer of the Original Code is 8x8 Inc.
 * Portions created by the Initial Developer are Copyright (C) 2005
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *   Alex Fritze <alex@croczilla.com> (original author)
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "nsISupports.idl"

interface zapISdpSessionDescription;
interface zapISdpMediaDescription;
interface zapISdpAttrib;
interface zapISdpTime;
interface zapISdpMediaFormat;
interface zapISdpConnection;

/**
 * SDP parsing service
 * Implemented by Component 5de0fd79-a03e-4640-ab99-186f5c66f5bb
 * ("@mozilla.org/zap/sdpservice;1")
 */
[scriptable, uuid(a4cb8b11-e2d4-4486-b190-4c1f818a0450)]
interface zapISdpService : nsISupports
{
  /**
   * Deserialize an rfc2327 session description into a
   * zapISdpSessionDescription object
   */
  zapISdpSessionDescription deserializeSessionDescription(in ACString octets);

  /**
   * Create a blank session description object
   */
  zapISdpSessionDescription createSessionDescription();

  /**
   * Create a blank connection field object
   */
  zapISdpConnection createConnection();
  
  /**
   * Create a blank media description object
   */
  zapISdpMediaDescription createMediaDescription();

  /**
   * Create a blank attribute field object
   */
  zapISdpAttrib createAttrib();

  /**
   * Create a blank time object
   */
  zapISdpTime createTime();

  /**
   * Create a blank media format object
   */
  zapISdpMediaFormat createMediaFormat();
};
