#!/bin/sh
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
#
# The contents of this file are subject to the Mozilla Public License Version
# 1.1 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
# The Original Code is a tool to determine a Mozilla objdir's build date
#
# The Initial Developer of the Original Code is Google Inc.
# Portions created by the Initial Developer are Copyright (C) 2006
# the Initial Developer. All Rights Reserved.
#
# Contributor(s):
#  Mark Mentovai <mark@moxienet.com> (Original Author)
#
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
#
# ***** END LICENSE BLOCK *****

# First, attempt to extract the bdate.

if test $# -ne 1 ; then
  echo "usage: $0 <objdir>" >&2
  exit 1
fi

if test -f $1/config/build_number ; then
  BDATE=`cat $1/config/build_number`
fi
BDATE_LEN=`echo $BDATE | wc -c`
if test -n "$BDATE" && test $BDATE_LEN -eq 11 && test "$BDATE" != "0000000000" ; then
  echo $BDATE
  exit 0
fi

# No bdate.  If it was an unofficial build, the bdate would have been zero,
# but the gbdate might be set.

if test -f $1/layout/build/gbdate.h ; then
  GBDATE=`grep PRODUCT_VERSION $1/layout/build/gbdate.h | sed -e 's/^.*"\([0-9]*\)".*$/\1/'`
fi
GBDATE_LEN=`echo $GBDATE | wc -c`
if test -n "$GBDATE" && test $GBDATE_LEN -eq 9 ; then
  # gbdate only has 1-day resolution, make up an hour
  echo "$GBDATE"00
  exit 0
fi

echo $0: no bdate >&2
exit 1
