/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is the Mozilla SIP client project.
 *
 * The Initial Developer of the Original Code is 8x8 Inc.
 * Portions created by the Initial Developer are Copyright (C) 2005
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *   Alex Fritze <alex@croczilla.com> (original author)
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "nsISupports.idl"

interface zapIMediaGraph;
interface zapIMediaSource;
interface zapIMediaSink;
interface nsIPropertyBag2;

%{ C++
#define ZAP_MEDIANODE_CONTRACTID_PREFIX "@mozilla.org/zap/medianode;type="
%}

[scriptable, uuid(8477a773-8b2e-4e8b-8ca7-d37886750074)]
interface zapIMediaNode : nsISupports
{
  /**
   * Called when this node is first added to a media graph.
   * 'id' is the identifier by which this node will be known
   * in 'graph'.
   */
  void addedToGraph(in zapIMediaGraph graph, in ACString id,
                    in nsIPropertyBag2 node_pars);

  /**
   * Called when this node is removed from the graph.
   * The framework will call this method only after all connections
   * have been disconnected.
   */
  void removedFromGraph(in zapIMediaGraph graph);

  /**
   * Return a source with the given parameters.
   * Throw error if the source as characterized by the parameter map
   * is not supported, if this is a sink-only node, or if the node
   * can't take any more connections.
   */
  zapIMediaSource getSource(in nsIPropertyBag2 source_pars);

  /**
   * Returns a sink with the given parameters.
   * Throws error if the sink as characterized by the parameter map
   * is not supported, if this is a source-only node, or if the node
   * can't take any more connections.
   */
  zapIMediaSink getSink(in nsIPropertyBag2 sink_pars);
};

