/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is the Mozilla SIP client project.
 *
 * The Initial Developer of the Original Code is 8x8 Inc.
 * Portions created by the Initial Developer are Copyright (C) 2006
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *   Alex Fritze <alex@croczilla.com> (original author)
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "nsISupports.idl"

/**
 * \ingroup ZMK_MODULE
 */
[scriptable, uuid(6b9450a4-2545-47f6-bebc-a0e27cad6c33)]
interface zapISpeexAudioProcessor : nsISupports
{
  /**
   * Toggles acoustic echo cancellation
   */
  attribute boolean aec;

  /**
   * Toggles 2 stage AEC
   */
  attribute boolean  aec2Stage;

  /**
   * AEC tail length in ms
   */
  attribute float aecTail;

  /**
   * Toggles denoising
   */
  attribute boolean denoise;

  /**
   * Toggles automatic gain control
   */
  attribute boolean agc;

  /**
   * AGC level (1 <= level <= 32768)
   */
  attribute float agcLevel;

  /**
   * Toggles voice activity detection
   */
  attribute boolean vad;

  /**
   * Toggles dereverb
   */
  attribute boolean dereverb;

  /**
   * Dereverb level
   */
  attribute float dereverbLevel;

  /**
   * Dereverb decay
   */
  attribute float dereverbDecay;

  /**
   * Reset speex preprocessor and AEC state
   */
  void reset();
};
